name: auth
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  conduit: ^4.4.0
  conduit_core: ^4.4.0
  conduit_postgresql: ^4.4.0
  jaguar_jwt: 3.0.0


dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
